[mongo]
uri = "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.1"

[credentials.usernames.jsmith]
email = "jsmith@gmail.com"
name = "John Smith"
password = "abc"

[credentials.usernames.rbriggs]
email = "rbriggs@gmail.com"
name = "Rebecca Briggs"
password = "def"

[cookie]
expiry_days = 30
key = "random_signature_key"
name = "random_cookie_name"

[preauthorized]
emails = [ "melsby@gmail.com" ]